version: '3.7'
services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "gaspar"
      POSTGRES_DB: "db_inventory"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./schemas:/var/lib/postgresql/data
    networks:
      docker_network:
        aliases:
          - postgresql_host

  pgadmin:
    image: dpage/pgadmin4:2023-09-18-1
    container_name: docker-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@patito.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    networks:
      docker_network:
        aliases:
          - postgresql_host

volumes:
  schemas: {}
networks:
  docker_network:
    name: postgresql_net
    driver: bridge