version: '3.7'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: docker-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "inventario"
      MYSQL_USER: "gaspar"
      MYSQL_PASSWORD: "123"
    volumes:
      - ./schemas:/var/lib/mysql
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
