
version: '3.7'

services:

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: docker-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ./schemas:/data/db
    networks:
      mongo_network:
        aliases:
          - mongo_host

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 80810:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      mongo_network:
        aliases:
          - mongo_host


networks:
  mongo_network:
    name: mongo_net
    driver: bridge